format = """
[░▒▓](#a3aed2)\
[ $os $username@$hostname ](fg:#090c0c bg:#a3aed2)\
[](fg:#a3aed2 bg:#769ff0)\
[ $directory ](fg:#e3e5e5 bg:#769ff0)\
[](fg:#769ff0 bg:#394260)\
[ $git_branch $git_status ](fg:#769ff0 bg:#394260)\
[](fg:#394260 bg:#212736)\
[ \
$rust\
$golang\
$deno\
 ](fg:#769ff0 bg:#212736)\
[](fg:#212736 bg:#1d2230)\
[  $time ](fg:#a0a9cb bg:#1d2230)\
[ ](fg:#1d2230)\
\n$character"""

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
format = "$user"
show_always = true

[hostname]
ssh_only = false
format = "$hostname"

[directory]
format = "$path"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
format = '$symbol $branch'

[git_status]
format = '$all_status$ahead_behind'

[rust]
symbol = ""
format = "$symbol ($version)"

[golang]
symbol = ""
format = "$symbol ($version)"

[deno]
format = "$symbol ($version)"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
format = '$time'

